from typing import List, Optional
from app.models.users import UserStatus, UserRole, GenderStatus, ServiceStatus,VerifyStatus, VerifyStatus


movies_db = [
  {
    "id": "001",
    "title": "The Shawshank Redemption",
    "category": "Drama",
    "description": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    "poster_url": "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    "trailer_url": "https://youtube.com/watch?v=6hB3S9bIaco",
    "duration": 142,
    "release_year": 1994,
    "rating": 9.3,
    "cast": "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler",
    "producer": "Frank Darabont",
    "views": 2847596,
    "created_at": "2025-11-06T19:41:56.895036",
    "updated_at": "2025-11-06T19:41:56.895043",
    "is_liked": True
  },
  {
    "id": "002",
    "title": "The Dark Knight",
    "category": "Action",
    "description": "When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological and physical tests to fight injustice.",
    "poster_url": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    "trailer_url": "https://youtube.com/watch?v=EXeTwQWrcwY",
    "duration": 152,
    "release_year": 2008,
    "rating": 9.0,
    "cast": "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine",
    "producer": "Christopher Nolan",
    "views": 3204568,
    "created_at": "2025-11-06T19:41:56.895840",
    "updated_at": "2025-11-06T19:41:56.895844",
    "is_liked": True
  },
  {
    "id": "003",
    "title": "The Lord of the Rings: The Return of the King",
    "category": "Fantasy",
    "description": "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    "poster_url": "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    "trailer_url": "https://youtube.com/watch?v=r7EHCsJ0dEU",
    "duration": 201,
    "release_year": 2003,
    "rating": 8.9,
    "cast": "Elijah Wood, Viggo Mortensen, Ian McKellen, Orlando Bloom",
    "producer": "Peter Jackson",
    "views": 2863865,
    "created_at": "2025-11-06T19:41:56.896260",
    "updated_at": "2025-11-06T19:41:56.896264",
    "is_liked": True
  },
  {
    "id": "004",
    "title": "Inception",
    "category": "Sci-Fi",
    "description": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
    "poster_url": "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
    "duration": 148,
    "release_year": 2010,
    "rating": 8.8,
    "cast": "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy",
    "producer": "Christopher Nolan",
    "views": 4175717,
    "created_at": "2025-11-06T19:41:56.896761",
    "updated_at": "2025-11-06T19:41:56.896764",
    "is_liked": True
  },
  {
    "id": "005",
    "title": "The Matrix",
    "category": "Sci-Fi",
    "description": "A computer hacker learns from mysterious rebels about the True nature of his reality and his role in the war against its controllers.",
    "poster_url": "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    "trailer_url": "https://youtube.com/watch?v=vKQi3bBA1y8",
    "duration": 136,
    "release_year": 1999,
    "rating": 8.7,
    "cast": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving",
    "producer": "The Wachowskis",
    "views": 3987942,
    "created_at": "2025-11-06T19:41:56.897405",
    "updated_at": "2025-11-06T19:41:56.897408",
    "is_liked": True
  },
  {
    "id": "006",
    "title": "The Lord of the Rings: The Fellowship of the Ring",
    "category": "Fantasy",
    "description": "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    "poster_url": "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    "trailer_url": "https://youtube.com/watch?v=V75dMMIW2B4",
    "duration": 178,
    "release_year": 2001,
    "rating": 8.8,
    "cast": "Elijah Wood, Ian McKellen, Orlando Bloom, Sean Bean",
    "producer": "Peter Jackson",
    "views": 2813676,
    "created_at": "2025-11-06T19:41:56.898003",
    "updated_at": "2025-11-06T19:41:56.898006",
    "is_liked": True
  },
  {
    "id": "007",
    "title": "The Silence of the Lambs",
    "category": "Thriller",
    "description": "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
    "poster_url": "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    "trailer_url": "https://youtube.com/watch?v=W6Mm8Sbe__o",
    "duration": 118,
    "release_year": 1991,
    "rating": 8.6,
    "cast": "Jodie Foster, Anthony Hopkins, Scott Glenn, Ted Levine",
    "producer": "Jonathan Demme",
    "views": 1891203,
    "created_at": "2025-11-06T19:41:56.898544",
    "updated_at": "2025-11-06T19:41:56.898550",
    "is_liked": True
  },
  {
    "id": "008",
    "title": "Interstellar",
    "category": "Sci-Fi",
    "description": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    "poster_url": "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    "trailer_url": "https://youtube.com/watch?v=zSWdZVtXT7E",
    "duration": 169,
    "release_year": 2014,
    "rating": 8.6,
    "cast": "Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine",
    "producer": "Christopher Nolan",
    "views": 3538318,
    "created_at": "2025-11-06T19:41:56.899574",
    "updated_at": "2025-11-06T19:41:56.899578",
    "is_liked": True
  },
  {
    "id": "009",
    "title": "Forrest Gump",
    "category": "Drama",
    "description": "The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
    "poster_url": "https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
    "trailer_url": "https://youtube.com/watch?v=bLvqoHBptjg",
    "duration": 142,
    "release_year": 1994,
    "rating": 8.8,
    "cast": "Tom Hanks, Robin Wright, Gary Sinise, Sally Field",
    "producer": "Robert Zemeckis",
    "views": 3932040,
    "created_at": "2025-11-06T19:41:56.900015",
    "updated_at": "2025-11-06T19:41:56.900018",
    "is_liked": True
  },
  {
    "id": "010",
    "title": "Gladiator",
    "category": "Action",
    "description": "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    "poster_url": "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    "trailer_url": "https://youtube.com/watch?v=owK1qxDselE",
    "duration": 155,
    "release_year": 2000,
    "rating": 8.5,
    "cast": "Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed",
    "producer": "Ridley Scott",
    "views": 2744137,
    "created_at": "2025-11-06T19:41:56.900665",
    "updated_at": "2025-11-06T19:41:56.900668",
    "is_liked": True
  },
  {
    "id": "011",
    "title": "Spirited Away",
    "category": "Animation",
    "description": "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits where humans are changed into beasts.",
    "poster_url": "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    "trailer_url": "https://youtube.com/watch?v=ByXuk9QqQkk",
    "duration": 125,
    "release_year": 2001,
    "rating": 8.6,
    "cast": "Rumi Hiiragi, Miyu Irino, Mari Natsuki, Takashi Naitō",
    "producer": "Hayao Miyazaki",
    "views": 1917624,
    "created_at": "2025-11-06T19:41:56.901099",
    "updated_at": "2025-11-06T19:41:56.901102",
    "is_liked": True
  },
  {
    "id": "012",
    "title": "Parasite",
    "category": "Thriller",
    "description": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    "poster_url": "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    "trailer_url": "https://youtube.com/watch?v=5xH0HfJHsaY",
    "duration": 132,
    "release_year": 2019,
    "rating": 8.6,
    "cast": "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik",
    "producer": "Bong Joon-ho",
    "views": 2872466,
    "created_at": "2025-11-06T19:41:56.902053",
    "updated_at": "2025-11-06T19:41:56.902056",
    "is_liked": True
  },
  {
    "id": "013",
    "title": "The Departed",
    "category": "Thriller",
    "description": "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
    "poster_url": "https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
    "trailer_url": "https://youtube.com/watch?v=iojhqm0JTW4",
    "duration": 151,
    "release_year": 2006,
    "rating": 8.5,
    "cast": "Leonardo DiCaprio, Matt Damon, Jack Nicholson, Mark Wahlberg",
    "producer": "Martin Scorsese",
    "views": 2583240,
    "created_at": "2025-11-06T19:41:56.902517",
    "updated_at": "2025-11-06T19:41:56.902520",
    "is_liked": True
  },
  {
    "id": "014",
    "title": "Pulp Fiction",
    "category": "Thriller",
    "description": "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    "poster_url": "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    "trailer_url": "https://youtube.com/watch?v=s7EdQ4FqbhY",
    "duration": 154,
    "release_year": 1994,
    "rating": 8.9,
    "cast": "John Travolta, Uma Thurman, Samuel L. Jackson, Bruce Willis",
    "producer": "Quentin Tarantino",
    "views": 3316379,
    "created_at": "2025-11-06T19:41:56.903104",
    "updated_at": "2025-11-06T19:41:56.903107",
    "is_liked": True
  },
  {
    "id": "015",
    "title": "The Godfather",
    "category": "Drama",
    "description": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    "poster_url": "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    "trailer_url": "https://youtube.com/watch?v=sY1S34973zA",
    "duration": 175,
    "release_year": 1972,
    "rating": 9.2,
    "cast": "Marlon Brando, Al Pacino, James Caan, Diane Keaton",
    "producer": "Francis Ford Coppola",
    "views": 4282294,
    "created_at": "2025-11-06T19:41:56.903570",
    "updated_at": "2025-11-06T19:41:56.903573",
    "is_liked": True
  },
  {
    "id": "016",
    "title": "Schindler's List",
    "category": "Drama",
    "description": "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution.",
    "poster_url": "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    "trailer_url": "https://youtube.com/watch?v=gG22XNhtnoY",
    "duration": 195,
    "release_year": 1993,
    "rating": 8.9,
    "cast": "Liam Neeson, Ralph Fiennes, Ben Kingsley, Caroline Goodall",
    "producer": "Steven Spielberg",
    "views": 2231386,
    "created_at": "2025-11-06T19:41:56.904522",
    "updated_at": "2025-11-06T19:41:56.904525",
    "is_liked": True
  },
  {
    "id": "017",
    "title": "WALL-E",
    "category": "Animation",
    "description": "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
    "poster_url": "https://image.tmdb.org/t/p/w500/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
    "trailer_url": "https://youtube.com/watch?v=CZ1CATNbXg0",
    "duration": 98,
    "release_year": 2008,
    "rating": 8.4,
    "cast": "Ben Burtt, Elissa Knight, Jeff Garlin, Fred Willard",
    "producer": "Andrew Stanton",
    "views": 2023335,
    "created_at": "2025-11-06T19:41:56.905118",
    "updated_at": "2025-11-06T19:41:56.905122",
    "is_liked": True
  },
  {
    "id": "018",
    "title": "The Green Mile",
    "category": "Drama",
    "description": "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder who has a mysterious gift.",
    "poster_url": "https://image.tmdb.org/t/p/w500/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
    "trailer_url": "https://youtube.com/watch?v=Ki4haFrqSrw",
    "duration": 189,
    "release_year": 1999,
    "rating": 8.6,
    "cast": "Tom Hanks, Michael Clarke Duncan, David Morse, Bonnie Hunt",
    "producer": "Frank Darabont",
    "views": 2175462,
    "created_at": "2025-11-06T19:41:56.906063",
    "updated_at": "2025-11-06T19:41:56.906066",
    "is_liked": True
  },
  {
    "id": "019",
    "title": "Django Unchained",
    "category": "Drama",
    "description": "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
    "poster_url": "https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
    "trailer_url": "https://youtube.com/watch?v=eUdM9vrCbow",
    "duration": 165,
    "release_year": 2012,
    "rating": 8.4,
    "cast": "Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington",
    "producer": "Quentin Tarantino",
    "views": 2910868,
    "created_at": "2025-11-06T19:41:56.907014",
    "updated_at": "2025-11-06T19:41:56.907017",
    "is_liked": True
  },
  {
    "id": "020",
    "title": "The Prestige",
    "category": "Drama",
    "description": "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
    "poster_url": "https://image.tmdb.org/t/p/w500/tRNlZbgNCNOpLpbPEz5L8G8A0JN.jpg",
    "trailer_url": "https://youtube.com/watch?v=o4gHCmTQDVI",
    "duration": 130,
    "release_year": 2006,
    "rating": 8.5,
    "cast": "Christian Bale, Hugh Jackman, Scarlett Johansson, Michael Caine",
    "producer": "Christopher Nolan",
    "views": 1986523,
    "created_at": "2025-11-06T19:41:56.907801",
    "updated_at": "2025-11-06T19:41:56.907804",
    "is_liked": True
  },
  {
    "id": "021",
    "title": "Fight Club",
    "category": "Drama",
    "description": "An insomniac office worker and a soap maker form an underground fight club that evolves into something much more dangerous.",
    "poster_url": "https://image.tmdb.org/t/p/w500/a26cQPRhJPX6GbWfQbvZdrrp9j9.jpg",
    "trailer_url": "https://youtube.com/watch?v=SUXWAEX2jlg",
    "duration": 139,
    "release_year": 1999,
    "rating": 8.8,
    "cast": "Brad Pitt, Edward Norton, Helena Bonham Carter",
    "producer": "David Fincher",
    "views": 4123456,
    "created_at": "2025-11-06T19:41:56.908301",
    "updated_at": "2025-11-06T19:41:56.908305",
    "is_liked": True
  },
  {
    "id": "022",
    "title": "The Witcher",
    "category": "Fantasy",
    "description": "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
    "poster_url": "https://image.tmdb.org/t/p/w500/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg",
    "trailer_url": "https://youtube.com/watch?v=ndl1W4ltcmg",
    "duration": 60,
    "release_year": 2019,
    "rating": 8.2,
    "cast": "Henry Cavill, Anya Chalotra, Freya Allan",
    "producer": "Lauren Schmidt Hissrich",
    "views": 3521789,
    "created_at": "2025-11-06T19:41:56.908701",
    "updated_at": "2025-11-06T19:41:56.908705",
    "is_liked": True
  },
  {
    "id": "023",
    "title": "The Old Guard",
    "category": "Action, Fantasy",
    "description": "A group of immortal warriors secretly protect humanity but face danger when their existence is exposed.",
    "poster_url": "https://image.tmdb.org/t/p/w500/cjr4NWURcVN3gW5FlHeabgBHLrY.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=aK-X2d0lJ_s",
    "duration": 125,
    "release_year": 2020,
    "rating": 6.7,
    "cast": "Charlize Theron, KiKi Layne, Marwan Kenzari, Matthias Schoenaerts",
    "producer": "David Ellison, Dana Goldberg, Don Granger, Charlize Theron",
    "views": 3987452,
    "created_at": "2025-11-06T19:41:56.909101",
    "updated_at": "2025-11-06T19:41:56.909105",
    "is_liked": True
  },
  {
    "id": "024",
    "title": "Superman",
    "category": "Superhero",
    "description": "A reboot of the Superman story following a young Clark Kent embracing his role as Earth’s protector.",
    "poster_url": "https://f.woowoowoowoo.net/resize/250x400/b4/cc/b4cc4dcecd4967a92791f386b9542cd1/b4cc4dcecd4967a92791f386b9542cd1.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=uhUht6vAsMY",
    "duration": 129,
    "release_year": 2025,
    "rating": 8.8,
    "cast": "David Corenswet, Rachel Brosnahan, Nicholas Hoult",
    "producer": "James Gunn, Peter Safran",
    "views": 2145678,
    "created_at": "2025-11-06T19:41:56.909501",
    "updated_at": "2025-11-06T19:41:56.909505",
    "is_liked": True
  },
  {
    "id": "025",
    "title": "Thunderbolts*",
    "category": "Action, Superhero",
    "description": "A government-assembled team of reformed villains takes on dangerous missions.",
    "poster_url": "https://f.woowoowoowoo.net/resize/250x400/3a/fa/3afa136c296584094ea6def1197425a9/3afa136c296584094ea6def1197425a9.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=Oe61Le-kmow",
    "duration": 127,
    "release_year": 2025,
    "rating": 9.0,
    "cast": "Florence Pugh, Sebastian Stan, David Harbour, Hannah John-Kamen",
    "producer": "Kevin Feige",
    "views": 2834561,
    "created_at": "2025-11-06T19:41:56.909901",
    "updated_at": "2025-11-06T19:41:56.909905",
    "is_liked": True
  },
  {
    "id": "026",
    "title": "A Minecraft Movie",
    "category": "Adventure, Fantasy",
    "description": "A group of real-world teenagers are transported into the Minecraft universe and must survive to return home.",
    "poster_url": "https://f.woowoowoowoo.net/resize/250x400/1a/c8/1ac845421ba06e68c5aface08a6ec274/1ac845421ba06e68c5aface08a6ec274.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=j8NQX7kzY2E",
    "duration": 101,
    "release_year": 2025,
    "rating": 7.5,
    "cast": "Jason Momoa, Jack Black, Emma Myers",
    "producer": "Mary Parent, Roy Lee",
    "views": 3218945,
    "created_at": "2025-11-06T19:41:56.910301",
    "updated_at": "2025-11-06T19:41:56.910305",
    "is_liked": True
  },
  {
    "id": "027",
    "title": "The Marvels",
    "category": "Action, Adventure, Science Fiction",
    "description": "Carol Danvers gets her powers entangled with those of Kamala Khan and Monica Rambeau, forcing them to work together to save the universe.",
    "poster_url": "https://www.fulguropop.com/wp-content/uploads/2023/11/marvels-poster-jpeg.webp",
    "trailer_url": "https://www.youtube.com/watch?v=wS_qbDztgVY",
    "duration": 105,
    "release_year": 2023,
    "rating": 6.5,
    "cast": "Brie Larson, Teyonah Parris, Iman Vellani, Samuel L. Jackson",
    "producer": "Kevin Feige",
    "views": 2876543,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "028",
    "title": "Wonka",
    "category": "Adventure, Comedy, Family, Fantasy",
    "description": "The story of how the world's greatest inventor, magician and chocolate-maker becomes the beloved Willy Wonka we know today.",
    "poster_url": "https://image.tmdb.org/t/p/w500/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=wYGOW33FePE",
    "duration": 116,
    "release_year": 2023,
    "rating": 7.1,
    "cast": "Timothée Chalamet, Olivia Colman, Hugh Grant, Keegan-Michael Key",
    "producer": "David Heyman",
    "views": 3567890,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "029",
    "title": "Oppenheimer",
    "category": "Biography, Drama, History",
    "description": "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    "poster_url": "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=uYPbbksJxIg",
    "duration": 180,
    "release_year": 2023,
    "rating": 8.3,
    "cast": "Cillian Murphy, Emily Blunt, Matt Damon, Robert Downey Jr.",
    "producer": "Christopher Nolan, Emma Thomas, Charles Roven",
    "views": 1987234,
    "created_at": "2025-11-06T19:41:56.911501",
    "updated_at": "2025-11-06T19:41:56.911505",
    "is_liked": True
  },
  {
    "id": "030",
    "title": "Dune: Part Two",
    "category": "Science Fiction, Adventure",
    "description": "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he must prevent a terrible future.",
    "poster_url": "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=Way9Dexny3w",
    "duration": 166,
    "release_year": 2024,
    "rating": 8.5,
    "cast": "Timothée Chalamet, Zendaya, Rebecca Ferguson, Austin Butler",
    "producer": "Denis Villeneuve, Mary Parent, Cale Boyter",
    "views": 1823456,
    "created_at": "2025-11-06T19:41:56.911901",
    "updated_at": "2025-11-06T19:41:56.911905",
    "is_liked": True
  },
  {
    "id": "031",
    "title": "Spider-Man: No Way Home",
    "category": "Action, Adventure, Science Fiction",
    "description": "Peter Parker's identity as Spider-Man is revealed, and he seeks Doctor Strange's help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Parker to discover what it truly means to be Spider-Man.",
    "poster_url": "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=JfVOs4VSpmA",
    "duration": 148,
    "release_year": 2021,
    "rating": 8.2,
    "cast": "Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon",
    "producer": "Kevin Feige, Amy Pascal",
    "views": 4876543,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "032",
    "title": "Barbie",
    "category": "Comedy, Adventure, Fantasy",
    "description": "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    "poster_url": "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=pBk4NYhWNMM",
    "duration": 114,
    "release_year": 2023,
    "rating": 7.0,
    "cast": "Margot Robbie, Ryan Gosling, America Ferrera, Kate McKinnon",
    "producer": "David Heyman, Margot Robbie, Tom Ackerley",
    "views": 5234567,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "033",
    "title": "Everything Everywhere All at Once",
    "category": "Action, Adventure, Science Fiction",
    "description": "An aging Chinese immigrant is swept up in an insane adventure where she alone can save the world by exploring other universes connecting with the lives she could have led.",
    "poster_url": "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=wxN1T1uxQ2g",
    "duration": 139,
    "release_year": 2022,
    "rating": 7.8,
    "cast": "Michelle Yeoh, Stephanie Hsu, Ke Huy Quan, Jamie Lee Curtis",
    "producer": "Dan Kwan, Daniel Scheinert, Jonathan Wang",
    "views": 3567890,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "034",
    "title": "Black Panther",
    "category": "Action, Adventure, Science Fiction",
    "description": "T'Challa returns home to the isolated, technologically advanced African nation of Wakanda to succeed to the throne and take his rightful place as king, but finds his claim challenged by a vengeful outsider.",
    "poster_url": "https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=xjDjIWPwcPU",
    "duration": 134,
    "release_year": 2018,
    "rating": 7.3,
    "cast": "Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o, Danai Gurira",
    "producer": "Kevin Feige",
    "views": 4123456,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "035",
    "title": "Avengers: Endgame",
    "category": "Action, Adventure, Science Fiction",
    "description": "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    "poster_url": "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    "duration": 181,
    "release_year": 2019,
    "rating": 8.4,
    "cast": "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth",
    "producer": "Kevin Feige",
    "views": 6234567,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "036",
    "title": "The Batman",
    "category": "Action, Crime, Drama",
    "description": "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a killer known as the Riddler.",
    "poster_url": "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=mqqft2x_Aa4",
    "duration": 176,
    "release_year": 2022,
    "rating": 7.8,
    "cast": "Robert Pattinson, Zoë Kravitz, Paul Dano, Jeffrey Wright",
    "producer": "Matt Reeves, Dylan Clark",
    "views": 3987654,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "037",
    "title": "Get Out",
    "category": "Horror, Mystery, Thriller",
    "description": "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.",
    "poster_url": "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=DzfpyUB60YY",
    "duration": 104,
    "release_year": 2017,
    "rating": 7.7,
    "cast": "Daniel Kaluuya, Allison Williams, Catherine Keener, Bradley Whitford",
    "producer": "Jason Blum, Edward H. Hamm Jr., Sean McKittrick",
    "views": 2876543,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "038",
    "title": "Knives Out",
    "category": "Comedy, Crime, Mystery",
    "description": "A detective investigates the death of a patriarch of an eccentric, combative family in this whodunit murder mystery.",
    "poster_url": "https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=qGqiHJTsRkQ",
    "duration": 130,
    "release_year": 2019,
    "rating": 7.9,
    "cast": "Daniel Craig, Ana de Armas, Chris Evans, Jamie Lee Curtis",
    "producer": "Rian Johnson, Ram Bergman",
    "views": 3234567,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "039",
    "title": "A Quiet Place",
    "category": "Horror, Drama, Science Fiction",
    "description": "In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.",
    "poster_url": "https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=WR7cc5t7tv8",
    "duration": 90,
    "release_year": 2018,
    "rating": 7.5,
    "cast": "Emily Blunt, John Krasinski, Millicent Simmonds, Noah Jupe",
    "producer": "Michael Bay, Andrew Form, Brad Fuller",
    "views": 2987654,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "040",
    "title": "La La Land",
    "category": "Comedy, Drama, Music, Romance",
    "description": "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
    "poster_url": "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=0pdqf4P9MB8",
    "duration": 128,
    "release_year": 2016,
    "rating": 8.0,
    "cast": "Ryan Gosling, Emma Stone, John Legend, Rosemarie DeWitt",
    "producer": "Fred Berger, Jordan Horowitz, Marc Platt",
    "views": 3456789,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "041",
    "title": "Joker",
    "category": "Crime, Drama, Thriller",
    "description": "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.",
    "poster_url": "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=zAGVQLHvwOY",
    "duration": 122,
    "release_year": 2019,
    "rating": 8.4,
    "cast": "Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy",
    "producer": "Todd Phillips, Bradley Cooper, Emma Tillinger Koskoff",
    "views": 4567890,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "042",
    "title": "Coco",
    "category": "Animation, Family, Adventure, Comedy",
    "description": "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
    "poster_url": "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=Rvr68u6k5sI",
    "duration": 105,
    "release_year": 2017,
    "rating": 8.4,
    "cast": "Anthony Gonzalez, Gael García Bernal, Benjamin Bratt, Alanna Ubach",
    "producer": "Darla K. Anderson",
    "views": 3678901,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "043",
    "title": "The Shape of Water",
    "category": "Drama, Fantasy, Romance",
    "description": "At a top secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity.",
    "poster_url": "https://image.tmdb.org/t/p/w500/9zfwPffUXpBrEP26yp0q1ckXDcj.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=XFYWazblaUA",
    "duration": 123,
    "release_year": 2017,
    "rating": 7.3,
    "cast": "Sally Hawkins, Octavia Spencer, Michael Shannon, Doug Jones",
    "producer": "Guillermo del Toro, J. Miles Dale",
    "views": 2456789,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "044",
    "title": "Thor: Ragnarok",
    "category": "Action, Adventure, Fantasy",
    "description": "Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarök, the destruction of his world, at the hands of the powerful and ruthless villain Hela.",
    "poster_url": "https://image.tmdb.org/t/p/w500/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=ue80QwXMRHg",
    "duration": 130,
    "release_year": 2017,
    "rating": 7.9,
    "cast": "Chris Hemsworth, Tom Hiddleston, Cate Blanchett, Mark Ruffalo",
    "producer": "Kevin Feige",
    "views": 3789012,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "045",
    "title": "Shang-Chi and the Legend of the Ten Rings",
    "category": "Action, Adventure, Fantasy",
    "description": "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
    "poster_url": "https://image.tmdb.org/t/p/w500/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=8YjFbMbfXaQ",
    "duration": 132,
    "release_year": 2021,
    "rating": 7.4,
    "cast": "Simu Liu, Awkwafina, Tony Leung, Michelle Yeoh",
    "producer": "Kevin Feige, Jonathan Schwartz",
    "views": 3123456,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "046",
    "title": "Encanto",
    "category": "Animation, Comedy, Family, Fantasy",
    "description": "A young Colombian girl has to face the frustration of being the only member of her family without magical powers in this Disney animated film.",
    "poster_url": "https://image.tmdb.org/t/p/w500/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=CaimKeDcudo",
    "duration": 102,
    "release_year": 2021,
    "rating": 7.2,
    "cast": "Stephanie Beatriz, María Cecilia Botero, John Leguizamo, Jessica Darrow",
    "producer": "Yvett Merino, Clark Spencer",
    "views": 4234569,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "047",
    "title": "Top Gun: Maverick",
    "category": "Action, Drama",
    "description": "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission that demands the ultimate sacrifice.",
    "poster_url": "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=qSqVVswa420",
    "duration": 130,
    "release_year": 2022,
    "rating": 8.3,
    "cast": "Tom Cruise, Miles Teller, Jennifer Connelly, Jon Hamm",
    "producer": "Jerry Bruckheimer, Tom Cruise, Christopher McQuarrie",
    "views": 4876543,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "048",
    "title": "The Super Mario Bros. Movie",
    "category": "Animation, Adventure, Family, Fantasy, Comedy",
    "description": "A plumber named Mario travels through an underground labyrinth with his brother Luigi, trying to save a captured princess.",
    "poster_url": "https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=TnGl01FkMMo",
    "duration": 92,
    "release_year": 2023,
    "rating": 7.0,
    "cast": "Chris Pratt, Anya Taylor-Joy, Charlie Day, Jack Black",
    "producer": "Chris Meledandri, Shigeru Miyamoto",
    "views": 4567890,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "049",
    "title": "Guardians of the Galaxy Vol. 3",
    "category": "Action, Adventure, Science Fiction",
    "description": "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and one of their own - a mission that could mean the end of the Guardians if not successful.",
    "poster_url": "https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=u3V5KDHRQvk",
    "duration": 150,
    "release_year": 2023,
    "rating": 7.9,
    "cast": "Chris Pratt, Zoe Saldana, Dave Bautista, Karen Gillan",
    "producer": "Kevin Feige",
    "views": 3987654,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  },
  {
    "id": "050",
    "title": "Inside Out 2",
    "category": "Animation, Family, Adventure, Comedy",
    "description": "Riley enters puberty and experiences brand new emotions as a result. As Riley tries to adapt to her teenage years, her old emotions try to adapt to the possibility of being replaced.",
    "poster_url": "https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    "trailer_url": "https://www.youtube.com/watch?v=LEjhY15eCx0",
    "duration": 96,
    "release_year": 2024,
    "rating": 7.6,
    "cast": "Amy Poehler, Maya Hawke, Kensington Tallman, Liza Lapira",
    "producer": "Mark Nielsen",
    "views": 4123456,
    "created_at": "2025-12-02T10:00:00.000000",
    "updated_at": "2025-12-02T10:00:00.000000",
    "is_liked": True
  }
]

user_db = [
  {
    "id": "001",
    "phone": "+233-50-460-9878",
    "email": "jfigueroa@example.com",
    "firstName": "Michael",
    "lastName": "Jones",
    "role": UserRole.CLIENT,
    "status": UserStatus.INACTIVE,
    "service": ServiceStatus.PREMIUM_PLUS,
    "profilePicture": "https://placehold.co/776x61",
    "dateOfbirth": "1976-10-31T00:00:00Z",
    "gender": GenderStatus.MALE,
    "bio": "Check example pretty key approach ground church one house others.",
    "location": {
      "lat": "30.642257",
      "lng": "150.455833"
    },
    "address": "35480 Cheryl Branch\nAllenborough, IN 16739",
    "isEmailVerified": VerifyStatus.REJECTED,
    "isPhoneVerified": VerifyStatus.PENDING,
    "watchlist": [],
    "preferences": {
      "theme": "light",
      "language": "fr"
    },
    "notificationSettings": {
      "emailNotifications": False,
      "smsNotifications": True,
      "pushNotifications": True
    },
    "createdAt": "2025-11-24T12:50:06Z",
    "updatedAt": "2025-11-24T12:50:06Z"
  },
  {
    "id": "002",
    "phone": "+233-20-798-3291",
    "email": "jonesnicole@example.com",
    "firstName": "Dennis",
    "lastName": "Lutz",
    "role": UserRole.ADMIN,
    "status": UserStatus.ACTIVE,
    "service": ServiceStatus.PREMIUM,
    "profilePicture": "https://placehold.co/97x115",
    "dateOfbirth": "1967-04-14T00:00:00Z",
    "gender": GenderStatus.MALE,
    "bio": "Stand both factor boy three sort bar ready discuss.",
    "location": {
      "lat": "81.646189",
      "lng": "18.699016"
    },
    "address": "98255 Bruce Shoal Suite 412\nRogerstown, ND 90475",
    "isEmailVerified": VerifyStatus.NOT_SUBMITTED,
    "isPhoneVerified": VerifyStatus.NOT_SUBMITTED,
    "watchlist": [],
    "preferences": {
      "theme": "dark",
      "language": "es"
    },
    "notificationSettings": {
      "emailNotifications": True,
      "smsNotifications": True,
      "pushNotifications": True
    },
    "createdAt": "2025-11-24T12:50:07Z",
    "updatedAt": "2025-11-24T12:50:07Z"
  },
  {
    "id": "003",
    "phone": "+233-23-911-5812",
    "email": "pedromurray@example.net",
    "firstName": "Veronica",
    "lastName": "Burgess",
    "role": UserRole.CLIENT,
    "status": UserStatus.SUSPENDED,
    "service": ServiceStatus.PREMIUM_PLUS,
    "profilePicture": "https://dummyimage.com/569x985",
    "dateOfbirth": "1991-08-29T00:00:00Z",
    "gender": GenderStatus.FEMALE,
    "bio": "Look record just note man available kid not social line.",
    "location": {
      "lat": "17.2769895",
      "lng": "-94.163715"
    },
    "address": "15992 Terry Ridges Apt. 134\nWest Russell, IN 17261",
    "isEmailVerified": VerifyStatus.APPROVED,
    "isPhoneVerified": VerifyStatus.APPROVED,
    "watchlist": [],
    "preferences": {
      "theme": "light",
      "language": "es"
    },
    "notificationSettings": {
      "emailNotifications": True,
      "smsNotifications": True,
      "pushNotifications": True
    },
    "createdAt": "2025-11-24T12:50:08Z",
    "updatedAt": "2025-11-24T12:50:08Z"
  },
  {
    "id": "004",
    "phone": "+233-24-809-2803",
    "email": "nmays@example.net",
    "firstName": "Aaron",
    "lastName": "Ray",
    "role": UserRole.CLIENT,
    "status": UserStatus.SUSPENDED,
    "service": ServiceStatus.PREMIUM,
    "profilePicture": "https://dummyimage.com/421x842",
    "dateOfbirth": "1963-04-15T00:00:00Z",
    "gender": GenderStatus.MALE,
    "bio": "Fund beyond wide boy though station conference these rich from.",
    "location": {
      "lat": "60.5782385",
      "lng": "-18.910336"
    },
    "address": "7675 Brown Rest\nEast Jason, NM 55778",
    "isEmailVerified": VerifyStatus.REJECTED,
    "isPhoneVerified": VerifyStatus.REJECTED,
    "watchlist": [],
    "preferences": {
      "theme": "dark",
      "language": "es"
    },
    "notificationSettings": {
      "emailNotifications": False,
      "smsNotifications": False,
      "pushNotifications": False
    },
    "createdAt": "2025-11-24T12:50:09Z",
    "updatedAt": "2025-11-24T12:50:09Z"
  },
  {
    "id": "005",
    "phone": "+233-54-244-2980",
    "email": "mporter@example.com",
    "firstName": "Heather",
    "lastName": "Kelly",
    "role": UserRole.CLIENT,
    "status": UserStatus.SUSPENDED,
    "service": ServiceStatus.PREMIUM,
    "profilePicture": "https://placehold.co/187x234",
    "dateOfbirth": "1980-11-11T00:00:00Z",
    "gender": GenderStatus.FEMALE,
    "bio": "Accept hard various conference here address model choice lay quality.",
    "location": {
      "lat": "-29.8803735",
      "lng": "-116.029759"
    },
    "address": "696 Nicole Overpass\nThompsonville, DC 05267",
    "isEmailVerified": VerifyStatus.NOT_SUBMITTED,
    "isPhoneVerified": VerifyStatus.APPROVED,
    "watchlist": [],
    "preferences": {
      "theme": "light",
      "language": "fr"
    },
    "notificationSettings": {
      "emailNotifications": False,
      "smsNotifications": False,
      "pushNotifications": True
    },
    "createdAt": "2025-11-24T12:50:10Z",
    "updatedAt": "2025-11-24T12:50:10Z"
  },
  {
    "id": "006",
    "phone": "+233-27-436-6960",
    "email": "dboyd@example.org",
    "firstName": "Amy",
    "lastName": "Wilson",
    "role": UserRole.CLIENT,
    "status": UserStatus.ACTIVE,
    "service": ServiceStatus.PREMIUM_PLUS,
    "profilePicture": "https://placehold.co/849x729",
    "dateOfbirth": "1989-08-26T00:00:00Z",
    "gender": GenderStatus.RATHER_NOT_SAY,
    "bio": "During step own type fish audience evidence property our rich western radio.",
    "location": {
      "lat": "-64.0076745",
      "lng": "-136.702135"
    },
    "address": "1323 Reese Forest Apt. 834\nEast Andrea, NE 11497",
    "isEmailVerified": VerifyStatus.APPROVED,
    "isPhoneVerified": VerifyStatus.NOT_SUBMITTED,
    "watchlist": [],
    "preferences": {
      "theme": "light",
      "language": "fr"
    },
    "notificationSettings": {
      "emailNotifications": False,
      "smsNotifications": True,
      "pushNotifications": True
    },
    "createdAt": "2025-11-24T12:50:08Z",
    "updatedAt": "2025-11-24T12:50:08Z"
  },
  {
    "id": "007",
    "phone": "+233-20-838-5642",
    "email": "hannah62@example.net",
    "firstName": "Melissa",
    "lastName": "White",
    "role": UserRole.CLIENT,
    "status": UserStatus.INACTIVE,
    "service": ServiceStatus.PREMIUM,
    "profilePicture": "https://placehold.co/514x749",
    "dateOfbirth": "1965-04-08T00:00:00Z",
    "gender": GenderStatus.NOT_SELECTED,
    "bio": "View hard speech education evening go drug series large choose general PM give contain keep fact.",
    "location": {
      "lat": "-52.6228695",
      "lng": "-19.402825"
    },
    "address": "67394 Hall Ferry Apt. 398\nLake Tara, UT 90969",
    "isEmailVerified": VerifyStatus.NOT_SUBMITTED,
    "isPhoneVerified": VerifyStatus.PENDING,
    "watchlist": [],
    "preferences": {
      "theme": "dark",
      "language": "en"
    },
    "notificationSettings": {
      "emailNotifications": True,
      "smsNotifications": False,
      "pushNotifications": False
    },
    "createdAt": "2025-11-24T12:50:08Z",
    "updatedAt": "2025-11-24T12:50:08Z"
  },
  {
    "id": "008",
    "phone": "+233-54-307-3056",
    "email": "elizabethmoore@example.org",
    "firstName": "Jacob",
    "lastName": "Ramirez",
    "role": UserRole.ADMIN,
    "status": UserStatus.SUSPENDED,
    "service": ServiceStatus.PREMIUM_PLUS,
    "profilePicture": "https://dummyimage.com/613x427",
    "dateOfbirth": "1997-03-22T00:00:00Z",
    "gender": GenderStatus.MALE,
    "bio": "Anything stay receive science store soldier relate within.",
    "location": {
      "lat": "-76.8606685",
      "lng": "-64.037914"
    },
    "address": "2022 Joshua Courts Apt. 838\nPort Nicole, WI 90265",
    "isEmailVerified": VerifyStatus.APPROVED,
    "isPhoneVerified": VerifyStatus.APPROVED,
    "watchlist": [],
    "preferences": {
      "theme": "light",
      "language": "fr"
    },
    "notificationSettings": {
      "emailNotifications": False,
      "smsNotifications": True,
      "pushNotifications": False
    },
    "createdAt": "2025-11-24T12:50:11Z",
    "updatedAt": "2025-11-24T12:50:11Z"
  },
  {
    "id": "009",
    "phone": "+233-24-304-7910",
    "email": "nancymcclain@example.net",
    "firstName": "Hannah",
    "lastName": "Payne",
    "role": UserRole.CLIENT,
    "status": UserStatus.ACTIVE,
    "service": ServiceStatus.FREE,
    "profilePicture": "https://placehold.co/606x172",
    "dateOfbirth": "1969-01-31T00:00:00Z",
    "gender": GenderStatus.RATHER_NOT_SAY,
    "bio": "Suffer single tell building wife you then for outside produce.",
    "location": {
      "lat": "-79.409332",
      "lng": "158.492886"
    },
    "address": "37348 Kennedy Crossing\nWest David, AR 90939",
    "isEmailVerified": VerifyStatus.APPROVED,
    "isPhoneVerified": VerifyStatus.PENDING,
    "watchlist": [],
    "preferences": {
      "theme": "dark",
      "language": "fr"
    },
    "notificationSettings": {
      "emailNotifications": False,
      "smsNotifications": False,
      "pushNotifications": True
    },
    "createdAt": "2025-11-24T12:50:12Z",
    "updatedAt": "2025-11-24T12:50:12Z"
  },
  {
    "id": "010",
    "phone": "+233-54-759-9029",
    "email": "sean57@example.com",
    "firstName": "Tiffany",
    "lastName": "Young",
    "role": UserRole.CLIENT,
    "status": UserStatus.SUSPENDED,
    "service": ServiceStatus.FREE,
    "profilePicture": "https://placehold.co/142x752",
    "dateOfbirth": "1977-03-27T00:00:00Z",
    "gender": GenderStatus.NOT_SELECTED,
    "bio": "Child bad drug appear prove public stay open also director same view minute manager director yet.",
    "location": {
      "lat": "-61.1882275",
      "lng": "67.776991"
    },
    "address": "9092 Courtney Crest Suite 283\nLake Omarhaven, IL 80734",
    "isEmailVerified": VerifyStatus.REJECTED,
    "isPhoneVerified": VerifyStatus.PENDING,
    "watchlist": [],
    "preferences": {
      "theme": "dark",
      "language": "es"
    },
    "notificationSettings": {
      "emailNotifications": True,
      "smsNotifications": False,
      "pushNotifications": False
    },
    "createdAt": "2025-11-24T12:50:10Z",
    "updatedAt": "2025-11-24T12:50:10Z"
  },
  {
    "id": "011",
    "phone": "+233-54-990-3206",
    "email": "colleensmith@example.com",
    "firstName": "Brooke",
    "lastName": "Miller",
    "role": UserRole.CLIENT,
    "status": UserStatus.SUSPENDED,
    "service": ServiceStatus.PREMIUM,
    "profilePicture": "https://placehold.co/420x190",
    "dateOfbirth": "1965-08-31T00:00:00Z",
    "gender": GenderStatus.FEMALE,
    "bio": "Those us drop pull collection fly commercial give professional nice us build cover animal next have.",
    "location": {
      "lat": "44.5786035",
      "lng": "-162.117485"
    },
    "address": "5497 Gilmore Bypass Apt. 416\nAdrienneshire, CT 22672",
    "isEmailVerified": VerifyStatus.APPROVED,
    "isPhoneVerified": VerifyStatus.REJECTED,
    "watchlist": [],
    "preferences": {
      "theme": "light",
      "language": "es"
    },
    "notificationSettings": {
      "emailNotifications": True,
      "smsNotifications": False,
      "pushNotifications": False
    },
    "createdAt": "2025-11-24T12:50:13Z",
    "updatedAt": "2025-11-24T12:50:13Z"
  },
  {
    "id": "012",
    "phone": "+233-20-485-2543",
    "email": "nicoleball@example.org",
    "firstName": "Melinda",
    "lastName": "Cooper",
    "role": UserRole.CLIENT,
    "status": UserStatus.ACTIVE,
    "service": ServiceStatus.FREE,
    "profilePicture": "https://dummyimage.com/8x455",
    "dateOfbirth": "1984-12-04T00:00:00Z",
    "gender": GenderStatus.FEMALE,
    "bio": "Success with father beautiful degree give have federal someone among book wide here job.",
    "location": {
      "lat": "79.790066",
      "lng": "64.207261"
    },
    "address": "26208 James Expressway Suite 722\nSouth Michaelborough, MT 35807",
    "isEmailVerified": VerifyStatus.REJECTED,
    "isPhoneVerified": VerifyStatus.REJECTED,
    "watchlist": [],
    "preferences": {
      "theme": "dark",
      "language": "en"
    },
    "notificationSettings": {
      "emailNotifications": True,
      "smsNotifications": True,
      "pushNotifications": True
    },
    "createdAt": "2025-11-24T12:50:14Z",
    "updatedAt": "2025-11-24T12:50:14Z"
  },
  {
    "id": "013",
    "phone": "+233-50-566-9975",
    "email": "jennifer67@example.org",
    "firstName": "Eric",
    "lastName": "Alexander",
    "role": UserRole.ADMIN,
    "status": UserStatus.INACTIVE,
    "service": ServiceStatus.PREMIUM,
    "profilePicture": "https://dummyimage.com/996x187",
    "dateOfbirth": "1984-03-04T00:00:00Z",
    "gender": GenderStatus.MALE,
    "bio": "Certain item community rise type standard health.",
    "location": {
      "lat": "-77.6904355",
      "lng": "157.715459"
    },
    "address": "USNS Harris\nFPO AP 69830",
    "isEmailVerified": VerifyStatus.APPROVED,
    "isPhoneVerified": VerifyStatus.NOT_SUBMITTED,
    "watchlist": [],
    "preferences": {
      "theme": "light",
      "language": "fr"
    },
    "notificationSettings": {
      "emailNotifications": False,
      "smsNotifications": True,
      "pushNotifications": True
    },
    "createdAt": "2025-11-24T12:50:12Z",
    "updatedAt": "2025-11-24T12:50:12Z"
  },
  {
    "id": "014",
    "phone": "+233-59-547-6154",
    "email": "ryan50@example.org",
    "firstName": "Michael",
    "lastName": "Meyers",
    "role": UserRole.ADMIN,
    "status": UserStatus.INACTIVE,
    "service": ServiceStatus.PREMIUM,
    "profilePicture": "https://dummyimage.com/807x736",
    "dateOfbirth": "2000-07-09T00:00:00Z",
    "gender": GenderStatus.MALE,
    "bio": "Himself scene among sit guy point now pull parent contain activity finish bank court degree.",
    "location": {
      "lat": "85.316912",
      "lng": "-100.637538"
    },
    "address": "21277 Samantha Neck Suite 720\nDavisshire, FM 08201",
    "isEmailVerified": VerifyStatus.APPROVED,
    "isPhoneVerified": VerifyStatus.APPROVED,
    "watchlist": [],
    "preferences": {
      "theme": "light",
      "language": "fr"
    },
    "notificationSettings": {
      "emailNotifications": True,
      "smsNotifications": False,
      "pushNotifications": False
    },
    "createdAt": "2025-11-24T12:50:13Z",
    "updatedAt": "2025-11-24T12:50:13Z"
  },
  {
    "id": "015",
    "phone": "+233-59-271-6703",
    "email": "theresa16@example.net",
    "firstName": "Jennifer",
    "lastName": "White",
    "role": UserRole.ADMIN,
    "status": UserStatus.INACTIVE,
    "service": ServiceStatus.FREE,
    "profilePicture": "https://dummyimage.com/412x771",
    "dateOfbirth": "1981-03-14T00:00:00Z",
    "gender": GenderStatus.FEMALE,
    "bio": "Catch tell administration drop full perform break week deep wrong direction money side across.",
    "location": {
      "lat": "67.4960905",
      "lng": "-119.645570"
    },
    "address": "069 Campbell Fork Apt. 762\nDanielfurt, NY 02556",
    "isEmailVerified": VerifyStatus.APPROVED,
    "isPhoneVerified": VerifyStatus.PENDING,
    "watchlist": [],
    "preferences": {
      "theme": "light",
      "language": "fr"
    },
    "notificationSettings": {
      "emailNotifications": True,
      "smsNotifications": False,
      "pushNotifications": True
    },
    "createdAt": "2025-11-24T12:50:15Z",
    "updatedAt": "2025-11-24T12:50:15Z"
  },
  {
    "id": "016",
    "phone": "+233-20-444-5307",
    "email": "nelsonstephanie@example.net",
    "firstName": "Jennifer",
    "lastName": "Brown",
    "role": UserRole.ADMIN,
    "status": UserStatus.ACTIVE,
    "service": ServiceStatus.PREMIUM_PLUS,
    "profilePicture": "https://placekitten.com/792/62",
    "dateOfbirth": "1962-05-23T00:00:00Z",
    "gender": GenderStatus.FEMALE,
    "bio": "Beyond cover safe cause national public choice say need she.",
    "location": {
      "lat": "-47.3366305",
      "lng": "-118.395846"
    },
    "address": "71549 Norris Walks Apt. 030\nLaurahaven, LA 65336",
    "isEmailVerified": VerifyStatus.PENDING,
    "isPhoneVerified": VerifyStatus.NOT_SUBMITTED,
    "watchlist": [],
    "preferences": {
      "theme": "dark",
      "language": "es"
    },
    "notificationSettings": {
      "emailNotifications": False,
      "smsNotifications": False,
      "pushNotifications": False
    },
    "createdAt": "2025-11-24T12:50:16Z",
    "updatedAt": "2025-11-24T12:50:16Z"
  },
  {
    "id": "017",
    "phone": "+233-20-160-7063",
    "email": "katie72@example.com",
    "firstName": "Mallory",
    "lastName": "Swanson",
    "role": UserRole.CLIENT,
    "status": UserStatus.ACTIVE,
    "service": ServiceStatus.PREMIUM_PLUS,
    "profilePicture": "https://dummyimage.com/872x355",
    "dateOfbirth": "1988-11-24T00:00:00Z",
    "gender": GenderStatus.RATHER_NOT_SAY,
    "bio": "Draw position sure easy on economy relate before.",
    "location": {
      "lat": "81.203346",
      "lng": "137.572299"
    },
    "address": "06549 Flowers Groves\nSouth Elizabeth, NV 05540",
    "isEmailVerified": VerifyStatus.PENDING,
    "isPhoneVerified": VerifyStatus.APPROVED,
    "watchlist": [],
    "preferences": {
      "theme": "light",
      "language": "fr"
    },
    "notificationSettings": {
      "emailNotifications": True,
      "smsNotifications": False,
      "pushNotifications": True
    },
    "createdAt": "2025-11-24T12:50:15Z",
    "updatedAt": "2025-11-24T12:50:15Z"
  },
  {
    "id": "018",
    "phone": "+233-20-623-2931",
    "email": "dcox@example.org",
    "firstName": "Brandon",
    "lastName": "Andrews",
    "role": UserRole.CLIENT,
    "status": UserStatus.ACTIVE,
    "service": ServiceStatus.PREMIUM_PLUS,
    "profilePicture": "https://dummyimage.com/931x858",
    "dateOfbirth": "1993-03-13T00:00:00Z",
    "gender": GenderStatus.MALE,
    "bio": "Southern join create mouth must growth expect wide drug may appear put staff girl decade.",
    "location": {
      "lat": "75.4481665",
      "lng": "-20.360215"
    },
    "address": "6322 Erica Shoals Apt. 120\nPort James, AK 14413",
    "isEmailVerified": VerifyStatus.PENDING,
    "isPhoneVerified": VerifyStatus.REJECTED,
    "watchlist": [],
    "preferences": {
      "theme": "dark",
      "language": "es"
    },
    "notificationSettings": {
      "emailNotifications": True,
      "smsNotifications": False,
      "pushNotifications": True
    },
    "createdAt": "2025-11-24T12:50:16Z",
    "updatedAt": "2025-11-24T12:50:16Z"
  },
  {
    "id": "019",
    "phone": "+233-59-880-5727",
    "email": "rhondacummings@example.net",
    "firstName": "Maria",
    "lastName": "Daniels",
    "role": UserRole.ADMIN,
    "status": UserStatus.INACTIVE,
    "service": ServiceStatus.PREMIUM,
    "profilePicture": "https://placehold.co/151x380",
    "dateOfbirth": "1970-10-10T00:00:00Z",
    "gender": GenderStatus.NOT_SELECTED,
    "bio": "Artist half religious first order degree despite write field might affect.",
    "location": {
      "lat": "-80.5208455",
      "lng": "136.323983"
    },
    "address": "8274 Jones Lakes\nOrozcoview, NC 01497",
    "isEmailVerified": VerifyStatus.PENDING,
    "isPhoneVerified": VerifyStatus.NOT_SUBMITTED,
    "watchlist": [],
    "preferences": {
      "theme": "dark",
      "language": "es"
    },
    "notificationSettings": {
      "emailNotifications": True,
      "smsNotifications": True,
      "pushNotifications": True
    },
    "createdAt": "2025-11-24T12:50:17Z",
    "updatedAt": "2025-11-24T12:50:17Z"
  },
  {
    "id": "020",
    "phone": "+233-20-518-2062",
    "email": "fweaver@example.com",
    "firstName": "Jose",
    "lastName": "Martin",
    "role": UserRole.ADMIN,
    "status": UserStatus.SUSPENDED,
    "service": ServiceStatus.PREMIUM,
    "profilePicture": "https://placehold.co/620x51",
    "dateOfbirth": "1994-03-18T00:00:00Z",
    "gender": GenderStatus.MALE,
    "bio": "Change their establish performance stock hold reality wish strategy.",
    "location": {
      "lat": "-74.236170",
      "lng": "30.295528"
    },
    "address": "831 Bradford Springs Apt. 366\nMichelleton, MD 98432",
    "isEmailVerified": VerifyStatus.PENDING,
    "isPhoneVerified": VerifyStatus.REJECTED,
    "watchlist": [],
    "preferences": {
      "theme": "dark",
      "language": "fr"
    },
    "notificationSettings": {
      "emailNotifications": False,
      "smsNotifications": True,
      "pushNotifications": False
    },
    "createdAt": "2025-11-24T12:50:18Z",
    "updatedAt": "2025-11-24T12:50:18Z"
  }
]
