from typing import List, Optional


movies_db = [
     {
        "id": "1",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
    {
        "id": "2",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
    {
        "id": "3",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
    {
        "id": "4",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
    {
        "id": "5",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
    {
        "id": "6",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
    {
        "id": "7",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
    {
        "id": "8",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
    {
        "id": "9",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
    {
        "id": "10",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
    {
        "id": "11",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
    {
        "id": "12",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
    {
        "id": "13",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
    {
        "id": "14",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
     {
        "id": "15",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
     {
        "id": "16",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
     {
        "id": "17",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
     {
        "id": "18",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
     {
        "id": "19",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    },
     {
        "id": "20",
        "title": "Inception",
        "category": "Sci-Fi",
        "description": "A thief who steals corporate secrets through dream-sharing.",
        "poster_url": "https://example.com/inception.jpg",
        "trailer_url": "https://youtube.com/watch?v=YoHD9XEInc0",
        "duration": 148,
        "release_year": 2010,
        "rating": 9.0,
        "cast": "Leonardo DiCaprio",
        "producer": "Christopher Nolan",
        "is_featured": True,
        "views": 50000,
        "created_at": "2025-01-01T00:00:00",
        "updated_at": "2025-01-01T00:00:00",
        "is_liked": True,
    }
]

user_db = [
    
]